---
abstract: 'Use Jifty model easily.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Test::More: 0
  Test::Warn: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: JiftyX-ModelHelpers
no_index:
  directory:
    - inc
    - t
version: 0.01
