--- 
abstract: Make it simpler to fetch records in Jifty.
author: 
  - Kang-min Liu <gugod@gugod.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: mit
name: JiftyX-ModelHelpers
requires: 
  Exporter: 0
  Jifty: 0.80408
version: 0.21
